# Python et algorithmie

Ecris une fonction qui prend un nombre entier compris entre 1 et 300 inclus, et le convertit en chiffre romains.

https://jeretiens.net/wp-content/uploads/2015/12/les_chiffres_romains.jpg
![Exemple de chiffres romains](https://jeretiens.net/wp-content/uploads/2015/12/les_chiffres_romains.jpg)

In [0]:
# Ta fonction ici :
def intToRom(nb):
  import numpy as np
  # décomposition du nombre en centaines, dizaines et unités.
  centaine = nb //100
  dizaine = nb // 10 - centaine*10
  unite = nb - dizaine*10 - centaine*100
  # table de correspondance des nombre romains 
  roms = np.array([['', 'I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX'], 
                   ['', 'X', 'XX', 'XXX', 'XL', 'L', 'LX', 'LXX', 'LXXX', 'XC'], 
                   ['', 'C', 'CC','CCC', 'CD', 'D', 'DC', 'DCC', 'DCCC', 'CM']])
  # conversion en nombre romain
  nb_roms = roms[2][centaine] + roms[1][dizaine] + roms[0][unite]
  # affiche la correspondance entre le nombre choisi et sa conversion 
  print(nb, ':', nb_roms)
  # retourne le nombre romain
  return nb_roms

intToRom(int(input()))

123
123 : CXXIII

'CXXIII'

# POO

**Programmation orientée objet**

Il t'est demandé de créer une nouvelle classe "sentence" qui va hériter de l'ensemble des méthodes de la classe "str" (*les chaines de caractères que tu connais bien en python*).

Tu devras ajouter une méthode .clean() qui nettoyera les espaces en début et en fin de chaine, mettra en majuscule le premier caractère, et tous les autres caractères en minuscule, et ajoutera un point "." à la fin.

Tu montreras le résultats en appliquant la méthode à la phrase ci-dessous.

In [0]:
# Tu mettras création de ta classe ici :
class sentence(str):
  def __init__(self, variable):
    str.__init__(self)
    self.variable = variable

  # method
  def clean(self):
    self.variable = self.variable.strip()
    self.variable = self.variable.lower()
    self.variable = self.variable[0].upper() + self.variable[1:]
    self.variable = self.variable + '.'
    print(self.variable)

# Ce code permettra de tester :
variable = " bonjour, AUJourd'hui c'EST le cheCKpoint   "
test = sentence(variable)
test.clean()

Bonjour, aujourd'hui c'est le checkpoint.

#NUMPY
Exécute le code suivant, puis réponds aux questions.

La matrice contient 12 colonnes correspondant chacune à un mois de l'année, et 31 lignes. Attention, certaines lignes ont des valeurs nulles pour les mois de 28 et 30 jours.

In [0]:
import numpy as np
import pandas as pd
temperatures_df = pd.read_csv("https://raw.githubusercontent.com/murpi/wilddata/master/temp2019.csv", skiprows = 3)
temperatures_df['jour'] = temperatures_df['DATE'].apply(lambda x: x[8:10])
temperatures_df['mois'] = temperatures_df['DATE'].apply(lambda x: x[5:7])
temperatures_array = temperatures_df.pivot_table(values = 'MAX_TEMPERATURE_C', index = 'jour' , columns='mois').to_numpy()
print("C'est chargé, ta matrice numpy est disponible sous le nom de variable : temperatures_array")

C'est chargé, ta matrice numpy est disponible sous le nom de variable : temperatures_array

In [0]:
print(temperatures_array)

[[ 9.  9. 14. 18. 17. 29. 24. 27. 23. 19. 17.  7.]
 [ 8.  7. 13. 12. 15. 23. 25. 29. 24. 19. 14.  7.]
 [ 6.  8. 14. 10. 15. 20. 26. 29. 26. 19. 14.  7.]
 [ 5.  7. 11. 10. 11. 19. 28. 26. 20. 17. 13.  8.]
 [ 6. 10. 13. 10. 12. 16. 30. 25. 19. 18. 12.  7.]
 [ 5. 12. 12. 10. 15. 18. 31. 23. 23. 18. 13. 11.]
 [10. 11. 11. 14. 14. 15. 28. 25. 22. 14. 11. 13.]
 [10. 11. 12. 12. 15. 18. 27. 28. 21. 18. 11. 13.]
 [ 7. 12. 13. 16. 15. 16. 25. 23. 17. 16. 10. 11.]
 [ 7. 11. 12. 14. 15. 17. 28. 23. 22. 18. 11. 11.]
 [10. 10. 11. 14. 16. 15. 26. 23. 22. 20. 11.  9.]
 [ 9. 12. 11. 14. 16. 16. 26. 22. 24. 21. 11. 12.]
 [10. 10. 10. 12. 16. 18. 27. 22. 28. 20.  9. 10.]
 [10. 13. 11.  9. 18. 19. 26. 20. 29. 20. 11. 12.]
 [ 9. 15. 13. 14. 18. 18. 26. 22. 31. 16.  8. 10.]
 [ 8. 14. 11. 15. 17. 19. 29. 22. 21. 16.  9. 11.]
 [ 9. 15. 11. 19. 17. 25. 27. 19. 27. 17.  8. 12.]
 [ 7. 12. 11. 21. 14. 28. 22. 21. 23. 16. 10. 12.]
 [11. 12. 12. 24. 17. 20. 26. 21. 23. 16.  9. 13.]
 [ 7. 13. 13. 21. 18. 20. 25. 23. 27. 15.  7. 12.]
 [ 7. 17. 15. 21. 20. 20. 26. 26. 28. 16. 11. 11.]
 [ 8. 17. 18. 19. 21. 23. 33. 28. 21. 16. 10. 10.]
 [ 7. 18. 17. 18. 21. 27. 39. 30. 20. 15. 12. 10.]
 [ 7. 14. 13. 14. 20. 23. 33. 33. 20. 14. 12. 14.]
 [11. 15. 12. 13. 19. 26. 32. 30. 17. 18. 13. 11.]
 [10. 19. 12. 14. 17. 31. 22. 33. 19. 19. 14. 12.]
 [ 8. 20. 13. 13. 19. 34. 23. 29. 19. 15. 13. 13.]
 [ 8. 13. 14. 12. 15. 34. 23. 24. 19. 12. 13. 11.]
 [ 9. nan 16. 16. 15. 32. 24. 25. 20. 14. 13.  9.]
 [ 7. nan 17. 18. 20. 26. 21. 30. 21. 17.  9. 12.]
 [ 8. nan 19. nan 25. nan 23. 23. nan 16. nan 10.]]

Questions

In [0]:
# Affiche un array numpy à partir de l'array "temperatures_array", 
# avec le nombre de jours par mois où la température a été inférieure à 10 degrés.

sum(temperatures_array < 10)

## correction
(temperatures_array < 10).sum(axis = 0)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in less

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in less
  after removing the cwd from sys.path.

array([23,  4,  0,  1,  0,  0,  0,  0,  0,  0,  7,  7])

In [0]:
# Idem avec la température entre 12 et 20 degrés

x = ((temperatures_array >= 12) & (temperatures_array <= 20))
sum(x)

## correction
((temperatures_array >= 12) & (temperatures_array <= 20)).sum(axis = 0)

# ou 
np.logical_and

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in greater_equal

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in less_equal

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in greater_equal

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in less_equal

array([ 0, 18, 22, 21, 27, 17,  0,  2, 10, 30, 13, 12])

In [5]:
# Au total sur l'année, combien y a-t-il eu de jours où la température était supérieure à 20 degrés ?

sum(sum(temperatures_array > 20)

## 
(temperatures_array > 20).sum()

101

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in greater

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in greater
  """

101

In [0]:
# Quelle a été la température moyenne du mois de mars ?

"""print(np.mean(temperatures_array[2]))"""

# correction

print(np.mean(temperatures_array[:, 2]))

13.064516129032258

In [8]:
# Quelle a été la température minimale du mois de juin ?

"""print(np.min(temperatures_array[5]))"""

# correction
print(np.min(temperatures_array[:29, 5]))

#
np.nanmin(temperatures_array[:, 5])

15.0

15.0

#SQL

A partir de la base de données client que [tu trouveras ici](https://www.w3schools.com/sql/trysql.asp?filename=trysql_op_in), crée une requête SQL qui fournit les **noms de chaque catégorie**, le **chiffre d'affaire associé à cette catégorie**, et le **prix moyen pondéré des produits vendus pour cette catégorie**. 

Le chiffre d'affaire sera arrondi à l'unité la plus proche, et le prix moyen comportera 2 décimales.

Ce tableau devra être trié pour avoir les catégories avec le chiffre d'affaire le plus élevé en premier.

Le code SQL devra être copié / collé dans un bloc de code ci-dessous.



*** Exemple des premières lignes attendues ***
*********************

Categories | Chiffre_d_affaire | Prix_moyen
- |:-: | -:
Beverages | 99465 | 43.45
Dairy Products | 69921 | 26.88
... | ... | ...

```sql 
-- Ton code SQL ici :
SELECT cat.CategoryName AS Categories, ROUND(SUM(p.price * od.Quantity)) AS Chiffre_d_affaire, ROUND(SUM(p.price * od.Quantity)/SUM(od.Quantity), 2) AS Prix_moyen 
FROM Products AS p
JOIN OrderDetails AS od ON od.ProductID = p.ProductID
JOIN Categories AS cat ON cat.CategoryID = p.CategoryID
GROUP BY Categories
ORDER BY Chiffre_d_affaire DESC
```

In [0]:
-- Ton code SQL ici :
SELECT cat.CategoryName AS Categories, ROUND(SUM(p.price * od.Quantity)) AS Chiffre_d_affaire, ROUND(SUM(p.price * od.Quantity)/SUM(od.Quantity), 2) AS Prix_moyen 
FROM Products AS p
JOIN OrderDetails AS od ON od.ProductID = p.ProductID
JOIN Categories AS cat ON cat.CategoryID = p.CategoryID
GROUP BY Categories
ORDER BY Chiffre_d_affaire DESC

# Tableur

Le responsable du reporting mensuel est absent, et il faut absolument envoyer le reporting de chiffre d'affaire (quantité * prix de chaque produit) aujourd'hui... mais impossible de remettre la main sur le fichier du mois dernier !

Heureusement, tu as trouvé comment extraire les données, [tu les trouveras ici.](https://docs.google.com/spreadsheets/d/1T7zh6Swn4Yj8Feu-xcp-B7xeOQfBoBSWn7sRjx07GvI/edit?usp=sharing)

Tu vas maintenant devoir recréer un graphique qui ressemblera au maximum à celui-ci, mais en incluant les données de mars 2020. Tu essaieras au maximum d'utiliser les tableaux croisés dynamiques pour faire ca.

Tu incluras l'image du graphique dans ce notebook, et tu indiqueras également le lien de ton google spreadsheet que tu auras pris soin de partager.

![Tableur checkpoint](https://github.com/murpi/wilddata/raw/master/checkpoint1.png)

![Graphique](https://docs.google.com/spreadsheets/d/e/2PACX-1vR44xO1f3C1UUDzH-l51Mt0GD22iW8gBqsDRpaMJOboceM4ry4mSL1vi7ms7X8UD6brIg6H-ofO69Sf/pubchart?oid=1221525009&format=image)